### ISSUE TITLE
ValueError: unmarshallable object

### ISSUE THREAD

**Issue by tansinjahan** [ajbrock/Generative-and-Discriminative-Voxel-Modelling#11]
Hi, 
I am getting an error whenever trying to run the GUI or train the VAE. I can understand this issue is related to CUDA but I would like to confirm the exact error and would appreciate any comments to help the problem solved. The error is following -

 ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 1, 'for cmd', 'nvcc -shared -O3 -m64 -Xcompiler -DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/tansin/.theano/compiledir_Linux-4.15--generic-x86_64-with-Ubuntu-18.04-bionic-x86_64-3.6.7-64/cuda_ndarray -I/usr/lib/python3/dist-packages/theano/sandbox/cuda -I/home/tansin/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -I/usr/lib/python3/dist-packages/theano/gof -L/usr/lib -o /home/tansin/.theano/compiledir_Linux-4.15--generic-x86_64-with-Ubuntu-18.04-bionic-x86_64-3.6.7-64/cuda_ndarray/cuda_ndarray.so mod.cu -lcublas -lpython3.6m -lcudart')
Traceback (most recent call last):
  File "Generative/train_VAE.py", line 522, in <module>
    main(args)
  File "Generative/train_VAE.py", line 336, in main
    config_module = imp.load_source('config', args.config_path)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 786, in get_code
  File "<frozen importlib._bootstrap_external>", line 503, in _code_to_bytecode
ValueError: unmarshallable object

**Comment by ajbrock** [comment]
Hi Tansin,

This might be related to the python version (this was trained with 2.7), but it might also have to do with Theano.

Theano (and a lot of the code that relies on it) isn't maintained anymore, and I'm not familiar with this error. You'll most likely need to run with the version of Theano this was built with (IIRC it was 0.7? sorry, I don't have it lying around at this point) to run it as-is. You're honestly better off porting all this to PyTorch (should only take an afternoon, plus two more debugging <_<) and running that instead. The GUI doesn't have any such external deprecated dependencies, VTK should be sufficient.
