### ISSUE TITLE
classification model: cannot import name checkpoints

### ISSUE THREAD

**Issue by sodaGH** [ajbrock/Generative-and-Discriminative-Voxel-Modelling#5]
I'm trying to run the train.py file of the Discriminative folder, but a problem arises at "from utils import checkpoints, metrics_logging", the problem is " ImportError: cannot import name checkpoints ".

Does anyone know how to fix it ?

**Comment by ajbrock** [comment]
Did you add the main folder to your PYTHONPATH or uncomment the sys.insert lines in the main files? I don't include any sort of install/setup.py file so you have to do that manually. You could also just undo the folder structure and put checkpoints/metrics logging in the main folder, then import then as "import checkpoints import metrics logging."

**Comment by sodaGH** [comment]
Hi, thanks for your reply. I have done as you told: 1) add the path to PYTHONPATH 2)uncomment the sys.insert lines 3)undo the folder structure and put checkpoints/metrics logging in the main folder 4) change the code " from utils import checkpoints, metrics_logging" into "import checkpoints
import metrics_logging". But the same problem is still there. "ImportError: No module named checkpoints". The train.py file is changed into this one:
[my_train.docx](https://github.com/ajbrock/Generative-and-Discriminative-Voxel-Modeling/files/969702/my_train.docx)

Wish to get your reply soon, do thanks a lot!

**Comment by ajbrock** [comment]
1. If you're going to uncomment the sys.insert lines they need to point to the correct path, that one is currently set for my path on my personal machine.

2. If you move the checkpoints/metrics_logging files into the main folder, you need to be sure you're running the my_train.py script from the appropriate folder. Try going into the python terminal (just type "python" at the command line) and entering "import checkpoints" to see which folders you can actually import checkpoints from. I recommend read up on the basics of importing/pythonic folder structure (e.g. in the python docs or on stackexchange).
